#!/bin/sh
# commit all changes to github with the commit text in $1

echo "Committing to git"
git status
echo "ADDING FILES"
git add -A
git status
echo "COMMITTING CHANGES"
git commit -m $1
git status
echo "PUSHING TO MASTER"
git push
echo "Done!!"